# Rustfmt configuration for fast-agent workspace
# See https://rust-lang.github.io/rustfmt/ for all available options

# Basic formatting options
edition = "2021"
max_width = 120
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

# Import organization
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
imports_layout = "Vertical"

# Function and struct formatting
fn_params_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
where_single_line = true

# Comments and documentation
wrap_comments = true
comment_width = 120
format_code_in_doc_comments = true
normalize_comments = true

# String formatting
format_strings = true
format_macro_matchers = true

# Other formatting options
use_field_init_shorthand = true
use_try_shorthand = true
force_explicit_abi = true
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false

# Error handling
error_on_line_overflow = false
error_on_unformatted = false
